<?php 
return [
	// Сфера деятельности
	[
		'parent_id' => null,
		'name' => 'field_of_activity',
		'title' => 'properties.field_of_activity',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.field_of_activity.description',
		'options' => [
		],
		'values' => [
			null => [
				// Срочно требуются
				'urgently_required' => 'properties.field_of_activity.urgently_required',
				// Руководящий состав
				'leadership' => 'properties.field_of_activity.leadership',
				// ИТР
				'engineering' => 'properties.field_of_activity.engineering',
				// Специалисты 
				'specialists' => 'properties.field_of_activity.specialists', 
				// Бухгалтерия 
				'accounting' => 'properties.field_of_activity.accounting', 
				// Менеджеры по продажам, агенты 
				'managers' => 'properties.field_of_activity.managers', 
				// Секретари, операторы 
				'secretaries' => 'properties.field_of_activity.secretaries', 
				// Торговля, продавцы 
				'trade' => 'properties.field_of_activity.trade', 
				// Медицина, аптеки  
				'medicine' => 'properties.field_of_activity.medicine', 
				// Пищевая промышленность  
				'food_industry' => 'properties.field_of_activity.food_industry', 
				// Строительные специальности 
				'building_specialties' => 'properties.field_of_activity.building_specialties', 
				// Рабочие специальности 
				'workers_specialties' => 'properties.field_of_activity.workers_specialties', 
				// Производство, заводы 
				'production' => 'properties.field_of_activity.production', 
				// Водители  
				'drivers' => 'properties.field_of_activity.drivers', 
				// Няни, домработницы  
				'housekeepers' => 'properties.field_of_activity.housekeepers', 
				// Работа вахтовым методом 
				'rotational_basis' => 'properties.field_of_activity.rotational_basis', 
				// Работа без опыта и специальности 
				'without_experience' => 'properties.field_of_activity.without_experience', 
				// Физический труд, разнорабочие
				'unskilled_workers' => 'properties.field_of_activity.unskilled_workers', 
				// Другая работа  
				'other' => 'properties.field_of_activity.other', 
				// Кадровые агентства 
				'recruitment_agencies' => 'properties.field_of_activity.recruitment_agencies', 
				// Образование  
				'education' => 'properties.field_of_activity.education', 
				// Частичная занятость и другие виды работ
				'part_time' => 'properties.field_of_activity.part_time', 
				// IT, интернет, телеком  
				'it' => 'properties.field_of_activity.it', 
				// Автомобильный бизнес  
				'auto' => 'properties.field_of_activity.auto', 
				// Административная работа 
				'admin' => 'properties.field_of_activity.admin', 
				// Банки, инвестиции 
				'banks' => 'properties.field_of_activity.banks', 
				// Без опыта, студенты  
				'students' => 'properties.field_of_activity.students', 
				// Бухгалтерия, финансы 
				'finance' => 'properties.field_of_activity.finance', 
				// Высший менеджмент 
				'management' => 'properties.field_of_activity.management', 
				// Госслужба, НКО  
				'state_service' => 'properties.field_of_activity.state_service', 
				// Домашний персонал
				'home_staff' => 'properties.field_of_activity.home_staff', 
				// ЖКХ, эксплуатация  
				'housing_and_utilities' => 'properties.field_of_activity.housing_and_utilities', 
				// Искусство, развлечения 
				'entertainment' => 'properties.field_of_activity.entertainment', 
				// Консультирование  
				'counseling' => 'properties.field_of_activity.counseling', 
				// Маркетинг, реклама, PR  
				'marketing' => 'properties.field_of_activity.marketing', 
				// Медицина, фармацевтика 
				'pharmaceuticals' => 'properties.field_of_activity.pharmaceuticals', 
				// Образование, наука  
				'science' => 'properties.field_of_activity.science', 
				// Охрана, безопасность  
				'security' => 'properties.field_of_activity.security', 
				// Продажи  
				'sales' => 'properties.field_of_activity.sales', 
				// Производство, сырьё, с/х
				'farming' => 'properties.field_of_activity.farming', 
				// Страхование 
				'insurance' => 'properties.field_of_activity.insurance', 
				// Строительство 
				'building' => 'properties.field_of_activity.building', 
				// Транспорт, логистика 
				'logistics' => 'properties.field_of_activity.logistics', 
				// Туризм, рестораны 
				'restaurants' => 'properties.field_of_activity.restaurants', 
				// Управление персоналом 
				'personnel_management' => 'properties.field_of_activity.personnel_management', 
				// Фитнес, салоны красоты
				'beauty_salons' => 'properties.field_of_activity.beauty_salons', 
				// Юриспруденция 
				'jurisprudence' => 'properties.field_of_activity.jurisprudence',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_employment',
		'title' => 'properties.type_of_employment',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_employment.description',
		'options' => [
		],
		'values' => [
			null => [
				'shift_method' => 'properties.type_of_employment.shift_method',
				'part_time' => 'properties.type_of_employment.part_time',
				'full_day' => 'properties.type_of_employment.full_day',
				'free_schedule' => 'properties.type_of_employment.free_schedule',
				'shift_work' => 'properties.type_of_employment.shift_work',
				'remote_work' => 'properties.type_of_employment.remote_work',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'working_conditions',
		'title' => 'properties.working_conditions',
		'type' => 'textarea',
		'default' => null,
		'description' => 'properties.working_conditions.description',
		'options' => [],
		'values' => [
			null => [null],
		],
	],
	[
		'parent_id' => null,
		'name' => 'requirements',
		'title' => 'properties.requirements',
		'type' => 'select',
		'default' => 'month',
		'description' => 'properties.requirements.description',
		'options' => [
		],
		'values' => [
			null => [
				'day' => 'properties.requirements.day',
				'hour' => 'properties.requirements.hour',
				'month' => 'properties.requirements.month',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'experience',
		'title' => 'properties.experience',
		'type' => 'numeric',
		'default' => '0',
		'description' => 'properties.experience.description',
		'options' => [
			'min' => 0,
			'max' => 50,
			'step' => 1,
			'format' => [0,',',' '],
			'view' => 'select', // input - поле ввода, select - выпадающий список
			'select-value' => 'properties.experience.value',
		],
		'values' => [
			null => [null],
		],
	],
	[
		'parent_id' => null,
		'name' => 'education',
		'title' => 'properties.education',
		'type' => 'select',
		'default' => 'month',
		'description' => 'properties.education.description',
		'options' => [
		],
		'values' => [
			null => [
				'higher_education' => 'properties.education.higher_education',
				'incomplete_higher_education' => 'properties.education.incomplete_higher_education',
				'average' => 'properties.education.average',
				'specialized_secondary' => 'properties.education.specialized_secondary',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'model',
		'title' => 'properties.model',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.model.description',
		'options' => [],
		'values' => [
			null => [
				'vaz' => 'properties.model.vaz',
				'gaz' => 'properties.model.gaz',
				'uaz' => 'properties.model.uaz',
				'audi' => 'properties.model.audi',
				'bmw' => 'properties.model.bmw',
				'chevrolet' => 'properties.model.chevrolet',
				'citroen' => 'properties.model.citroen',
				'daewoo' => 'properties.model.daewoo',
				'fiat' => 'properties.model.fiat',
				'ford' => 'properties.model.ford',
				'honda' => 'properties.model.honda',
				'hyundai' => 'properties.model.hyundai',
				'infiniti' => 'properties.model.infiniti',
				'kia' => 'properties.model.kia',
				'land_rover' => 'properties.model.land_rover',
				'lexus' => 'properties.model.lexus',
				'mazda' => 'properties.model.mazda',
				'mercedes_benz' => 'properties.model.mercedes_benz',
				'mitsubishi' => 'properties.model.mitsubishi',
				'nissan' => 'properties.model.nissan',
				'opel' => 'properties.model.opel',
				'peugeot' => 'properties.model.peugeot',
				'porsche' => 'properties.model.porsche',
				'renault' => 'properties.model.renault',
				'porsche' => 'properties.model.porsche',
				'skoda' => 'properties.model.skoda',
				'ssangyong' => 'properties.model.ssangyong',
				'subaru' => 'properties.model.subaru',
				'suzuki' => 'properties.model.suzuki',
				'toyota' => 'properties.model.toyota',
				'volkswagen' => 'properties.model.volkswagen',
				'volvo' => 'properties.model.volvo',
				'other' => 'properties.model.other',
			],
		],
	],
	[
		'parent_id' => 'model',
		'name' => 'series',
		'title' => 'properties.series',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.series.description',
		'options' => [],
		'values' => [
			'vaz' => [
				'1111' => 'properties.series.1111',
				'oка' => 'properties.series.oка',
				'2101' => 'properties.series.2101',
				'2102' => 'properties.series.2102',
				'2103' => 'properties.series.2103',
				'2104' => 'properties.series.2104',
				'2105' => 'properties.series.2105',
				'2106' => 'properties.series.2106',
				'2107' => 'properties.series.2107',
				'2108' => 'properties.series.2108',
				'2109' => 'properties.series.2109',
				'21099' => 'properties.series.21099',
				'2110' => 'properties.series.2110',
				'2111' => 'properties.series.2111',
				'2112' => 'properties.series.2112',
				'2113' => 'properties.series.2113',
				'2114' => 'properties.series.2114',
				'2115' => 'properties.series.2115',
				'2120' => 'properties.series.2120',
				'2123' => 'properties.series.2123',
				'4x4' => 'properties.series.4x4',
				'granta' => 'properties.series.granta',
				'kalina' => 'properties.series.kalina',
				'largus' => 'properties.series.largus',
				'priora' => 'properties.series.priora',
				'vesta' => 'properties.series.vesta',
				'xray' => 'properties.series.xray',
				'other' => 'properties.series.other',
			],
			'gaz' => [
				'12_zim' => 'properties.series.12_zim',
				'13_chayka' => 'properties.series.13_chayka',
				'14_chayka' => 'properties.series.14_chayka',
				'М_20_pobeda' => 'properties.series.М_20_pobeda',
				'21_volga' => 'properties.series.21_volga',
				'22_volga' => 'properties.series.22_volga',
				'24_volga' => 'properties.series.24_volga',
				'310221_volga' => 'properties.series.310221_volga',
				'31029_volga' => 'properties.series.31029_volga',
				'3102_volga' => 'properties.series.3102_volga',
				'31105_volga' => 'properties.series.31105_volga',
				'3110_volga' => 'properties.series.3110_volga',
				'3111_volga' => 'properties.series.3111_volga',
				'volga_siber' => 'properties.series.volga_siber',
				'gazel' => 'properties.series.gazel',
				'gazel_2705' => 'properties.series.gazel_2705',
				'gazel_3221' => 'properties.series.gazel_3221',
				'gazel_3302'  => 'properties.series.gazel_3302',
				'gazel_33023' => 'properties.series.gazel_33023',
				'gazel_next' => 'properties.series.gazel_next',
				'sobol' => 'properties.series.sobol',
				'sobol_2217' => 'properties.series.sobol_2217',
				'sobol_2310' => 'properties.series.sobol_2310',
				'sobol_2752' => 'properties.series.sobol_2752',
				'other' => 'properties.series.other',
			],
			'uaz' => [
				'2206' => 'properties.series.2206',
				'3151' => 'properties.series.3151',
				'31512' => 'properties.series.31512',
				'31514' => 'properties.series.31514',
				'31519' => 'properties.series.31519',
				'3153' => 'properties.series.3153',
				'3159' => 'properties.series.3159',
				'3303' => 'properties.series.3303',
				'3741' => 'properties.series.3741',
				'3909' => 'properties.series.3909',
				'452_bukanka' => 'properties.series.452_bukanka',
				'469' => 'properties.series.469',
				'hunter' => 'properties.series.hunter',
				'patriot' => 'properties.series.patriot',
				'pickup'  => 'properties.series.pickup',
				'kargo' => 'properties.series.kargo',
				'simbit' => 'properties.series.simbit',
				'other' => 'properties.series.other',
			],
			'audi' => [
				'100' => 'properties.series.100',
				'200' => 'properties.series.200',
				'80' => 'properties.series.80',
				'90' => 'properties.series.90',
				'a1' => 'properties.series.a1',
				'a3' => 'properties.series.a3',
				'a4' => 'properties.series.a4',
				'a4_allroad_quattro' => 'properties.series.a4_allroad_quattro',
				'a5' => 'properties.series.a5',
				'a6' => 'properties.series.a6',
				'a6_allroad_quattro' => 'properties.series.a6_allroad_quattro',
				'a7' => 'properties.series.a7',
				'a8' => 'properties.series.a8',
				'coupe' => 'properties.series.coupe',
				'q3' => 'properties.series.q3',
				'q5' => 'properties.series.q5',
				'q7'  => 'properties.series.q7',
				'r8' => 'properties.series.r8',
				'rs4' => 'properties.series.rs4',
				'rs5' => 'properties.series.rs5',
				'rs6' => 'properties.series.rs6',
				'rs7' => 'properties.series.rs7',
				'rs_q3' => 'properties.series.rs_q3',
				's1' => 'properties.series.s1',
				's3' => 'properties.series.s3',
				's4' => 'properties.series.s4',
				's5' => 'properties.series.s5',
				's6' => 'properties.series.s6',
				's8' => 'properties.series.s8',
				'sq5' => 'properties.series.sq5',
				'tt' => 'properties.series.tt',
				'tt_rs' => 'properties.series.tt_rs',
				'tts' => 'properties.series.tts',
				'v8' => 'properties.series.v8',
				'other' => 'properties.series.other',
			],
			'bmw' => [
				'1_series' => 'properties.series.1_series',
				'2_series' => 'properties.series.2_series',
				'3_series' => 'properties.series.3_series',
				'3_series_GT' => 'properties.series.3_series_GT',
				'4_series' => 'properties.series.4_series',
				'5_series' => 'properties.series.5_series',
				'5_series_GT' => 'properties.series.5_series_GT',
				'6_series' => 'properties.series.6_series',
				'7_series' => 'properties.series.7_series',
				'8_series' => 'properties.series.8_series',
				'i3' => 'properties.series.i3',
				'i8' => 'properties.series.i8',
				'M3' => 'properties.series.M3',
				'M4'  => 'properties.series.M4',
				'M5' => 'properties.series.M5',
				'M6' => 'properties.series.M6',
				'X1' => 'properties.series.X1',
				'X3' => 'properties.series.X3',
				'X4' => 'properties.series.X4',
				'X5' => 'properties.series.X5',
				'X5_M' => 'properties.series.X5_M',
				'X6' => 'properties.series.X6',
				'X6_M' => 'properties.series.X6_M',
				'Z3' => 'properties.series.Z3',
				'Z4' => 'properties.series.Z4',
				'Z4_M' => 'properties.series.Z4_M',
				'other' => 'properties.series.other',
			],
			'chevrolet' => [
				'alero' => 'properties.series.alero',
				'avalanche' => 'properties.series.avalanche',
				'aveo' => 'properties.series.aveo',
				'blazer' => 'properties.series.blazer',
				'camaro' => 'properties.series.camaro',
				'caprice' => 'properties.series.caprice',
				'captiva' => 'properties.series.captiva',
				'cavalier' => 'properties.series.cavalier',
				'cobalt' => 'properties.series.cobalt',
				'corvette' => 'properties.series.corvette',
				'cruze' => 'properties.series.cruze',
				'epica' => 'properties.series.epica',
				'evanda'  => 'properties.series.evanda',
				'express' => 'properties.series.express',
				'lacetti' => 'properties.series.lacetti',
				'lanos' => 'properties.series.lanos',
				'lumina' => 'properties.series.lumina',
				'malibu' => 'properties.series.malibu',
				'niva' => 'properties.series.niva',
				'orlando' => 'properties.series.orlando',
				'rezzo' => 'properties.series.rezzo',
				'silverado' => 'properties.series.silverado',
				'spark' => 'properties.series.spark',
				'suburban' => 'properties.series.suburban',
				'tahoe' => 'properties.series.tahoe',
				'tracker'  => 'properties.series.tracker',
				'trailBlazer' => 'properties.series.trailBlazer',
				'van' => 'properties.series.van',
				'viva' => 'properties.series.viva',
				'other' => 'properties.series.other',
			],
			'citroen' => [
				'berlingo' => 'properties.series.berlingo',
				'bx' => 'properties.series.bx',
				'c1' => 'properties.series.c1',
				'c2' => 'properties.series.c2',
				'c3' => 'properties.series.c3',
				'c3_picasso' => 'properties.series.c3_picasso',
				'c4' => 'properties.series.c4',
				'c4_aircross' => 'properties.series.c4_aircross',
				'c4_picasso' => 'properties.series.c4_picasso',
				'c5' => 'properties.series.c5',
				'c6' => 'properties.series.c6',
				'c8' => 'properties.series.c8',
				'c_crosser' => 'properties.series.c_crosser',
				'c_elysee'  => 'properties.series.c_elysee',
				'ds3' => 'properties.series.ds3',
				'ds4' => 'properties.series.ds4',
				'ds5' => 'properties.series.ds5',
				'grand_c4_picasso' => 'properties.series.grand_c4_picasso',
				'jumper' => 'properties.series.jumper',
				'jumpy' => 'properties.series.jumpy',
				'nemo' => 'properties.series.nemo',
				'daxo' => 'properties.series.daxo',
				'xm' => 'properties.series.xm',
				'xsara' => 'properties.series.xsara',
				'xsara_picasso' => 'properties.series.xsara_picasso',
				'other' => 'properties.series.other',
			],
			'daewoo' => [
				'espero' => 'properties.series.espero',
				'evanda' => 'properties.series.evanda',
				'gentra' => 'properties.series.gentra',
				'lacetti' => 'properties.series.lacetti',
				'lanos' => 'properties.series.lanos',
				'leganza' => 'properties.series.leganza',
				'magnus' => 'properties.series.magnus',
				'matiz' => 'properties.series.matiz',
				'nexia' => 'properties.series.nexia',
				'nubira' => 'properties.series.nubira',
				'tico' => 'properties.series.tico',
				'winstorm' => 'properties.series.winstorm',
				'other' => 'properties.series.other',
			],
			'fiat' => [
				'albea' => 'properties.series.albea',
				'brava' => 'properties.series.brava',
				'bravo' => 'properties.series.bravo',
				'doblo' => 'properties.series.doblo',
				'linea' => 'properties.series.linea',
				'panda' => 'properties.series.panda',
				'punto' => 'properties.series.punto',
				'scudo' => 'properties.series.scudo',
				'sedici' => 'properties.series.sedici',
				'stilo' => 'properties.series.stilo',
				'other' => 'properties.series.other',
			],
			'ford' => [
				'c_max' => 'properties.series.c_max',
				'econoline' => 'properties.series.econoline',
				'ecosport' => 'properties.series.ecosport',
				'escape' => 'properties.series.escape',
				'escort' => 'properties.series.escort',
				'expedition' => 'properties.series.expedition',
				'explorer' => 'properties.series.explorer',
				'f_150' => 'properties.series.f_150',
				'f_250' => 'properties.series.f_250',
				'f_350' => 'properties.series.f_350',
				'fiesta' => 'properties.series.fiesta',
				'focus' => 'properties.series.focus',
				'focus_st' => 'properties.series.focus_st',
				'fusion' => 'properties.series.fusion',
				'galaxy' => 'properties.series.galaxy',
				'ka' => 'properties.series.ka',
				'kuga' => 'properties.series.kuga',
				'maverick' => 'properties.series.maverick',
				'mondeo' => 'properties.series.mondeo',
				'mustang' => 'properties.series.mustang',
				'probe' => 'properties.series.probe',
				'ranger' => 'properties.series.ranger',
				'scorpio' => 'properties.series.scorpio',
				's_max' => 'properties.series.s_max',
				'taurus' => 'properties.series.taurus',
				'tourneo' => 'properties.series.tourneo',
				'tourneo_connect' => 'properties.series.tourneo_connect',
				'transit' => 'properties.series.transit',
				'windstar' => 'properties.series.windstar',
				'other' => 'properties.series.other',
			],
			'honda' => [
				'accord' => 'properties.series.accord',
				'airwave' => 'properties.series.airwave',
				'civic' => 'properties.series.civic',
				'crosstour' => 'properties.series.crosstour',
				'cr_v' => 'properties.series.cr_v',
				'cr_x' => 'properties.series.cr_x',
				'cr_z' => 'properties.series.cr_z',
				'element' => 'properties.series.element',
				'fit' => 'properties.series.fit',
				'hr_v' => 'properties.series.hr_v',
				'insight' => 'properties.series.insight',
				'integra' => 'properties.series.integra',
				'jazz' => 'properties.series.jazz',
				'legend' => 'properties.series.legend',
				'logo' => 'properties.series.logo',
				'mobilio' => 'properties.series.mobilio',
				'odyssey' => 'properties.series.odyssey',
				'orthia' => 'properties.series.orthia',
				'partner' => 'properties.series.partner',
				'pilot' => 'properties.series.pilot',
				'prelude' => 'properties.series.prelude',
				'ridgeline' => 'properties.series.ridgeline',
				'saber' => 'properties.series.saber',
				'shuttle' => 'properties.series.shuttle',
				'stepwgn' => 'properties.series.stepwgn',
				'stream' => 'properties.series.stream',
				'torneo' => 'properties.series.torneo',
				'vamos' => 'properties.series.vamos',
				'zest' => 'properties.series.zest',
				'other' => 'properties.series.other',
			],
			'hyundai' => [
				'accent' => 'properties.series.accent',
				'coupe' => 'properties.series.coupe',
				'creta' => 'properties.series.creta',
				'elantra' => 'properties.series.elantra',
				'equus' => 'properties.series.equus',
				'galloper' => 'properties.series.galloper',
				'genesis' => 'properties.series.genesis',
				'getz' => 'properties.series.getz',
				'grandeur' => 'properties.series.grandeur',
				'h_100' => 'properties.series.h_100',
				'h_1_grand_starex' => 'properties.series.h_1grand_starex',
				'i20' => 'properties.series.i20',
				'i30' => 'properties.series.i30',
				'i40' => 'properties.series.i40',
				'ix35' => 'properties.series.ix35',
				'ix55' => 'properties.series.ix55',
				'lantra' => 'properties.series.lantra',
				'matrix' => 'properties.series.matrix',
				'nf' => 'properties.series.nf',
				'porter' => 'properties.series.porter',
				'santa_fe' => 'properties.series.santa_fe',
				'solaris' => 'properties.series.solaris',
				'sonata' => 'properties.series.sonata',
				'starex' => 'properties.series.starex',
				'terracan' => 'properties.series.terracan',
				'tiburon' => 'properties.series.tiburon',
				'trajet' => 'properties.series.trajet',
				'tucson' => 'properties.series.tucson',
				'veloster' => 'properties.series.veloster',
				'other' => 'properties.series.other',
			],
			'infiniti' => [
				'ex25' => 'properties.series.ex25',
				'ex35' => 'properties.series.ex35',
				'ex37' => 'properties.series.ex37',
				'fx30' => 'properties.series.fx30',
				'fx35' => 'properties.series.fx35',
				'fx37' => 'properties.series.fx37',
				'fx45' => 'properties.series.fx45',
				'fx50' => 'properties.series.fx50',
				'g20' => 'properties.series.g20',
				'g25' => 'properties.series.g25',
				'g35' => 'properties.series.g35',
				'g37' => 'properties.series.g37',
				'i30' => 'properties.series.i30',
				'j30' => 'properties.series.j30',
				'jx' => 'properties.series.jx',
				'm25' => 'properties.series.m25',
				'm30' => 'properties.series.m30',
				'm35' => 'properties.series.m35',
				'm37' => 'properties.series.m37',
				'm45' => 'properties.series.m45',
				'm56' => 'properties.series.m56',
				'q45' => 'properties.series.q45',
				'q50' => 'properties.series.q50',
				'q70' => 'properties.series.q70',
				'qx4' => 'properties.series.qx4',
				'qx50' => 'properties.series.qx50',
				'qx56' => 'properties.series.qx56',
				'qx60' => 'properties.series.qx60',
				'qx70' => 'properties.series.qx70',
				'qx80' => 'properties.series.qx80',
				'other' => 'properties.series.other',
			],
			'kia' => [
				'avella' => 'properties.series.avella',
				'besta' => 'properties.series.besta',
				'cadenza' => 'properties.series.cadenza',
				'carens' => 'properties.series.carens',
				'carnival' => 'properties.series.carnival',
				'cee_d' => 'properties.series.cee_d',
				'cee_d_gt' => 'properties.series.cee_d_gt',
				'cerato' => 'properties.series.cerato',
				'clarus' => 'properties.series.clarus',
				'joice' => 'properties.series.joice',
				'k' => 'properties.series.k',
				'magentis' => 'properties.series.magentis',
				'mohave' => 'properties.series.mohave',
				'opirus' => 'properties.series.opirus',
				'optima' => 'properties.series.optima',
				'picanto' => 'properties.series.picanto',
				'quoris' => 'properties.series.quoris',
				'rio' => 'properties.series.rio',
				'sephia' => 'properties.series.sephia',
				'shuma' => 'properties.series.shuma',
				'sorento' => 'properties.series.sorento',
				'soul' => 'properties.series.soul',
				'spectra' => 'properties.series.spectra',
				'sportage' => 'properties.series.sportage',
				'venga' => 'properties.series.venga',
				'other' => 'properties.series.other',
			],
			'land_rover' => [
				'defender' => 'properties.series.defender',
				'discovery' => 'properties.series.discovery',
				'discovery sport' => 'properties.series.discovery sport',
				'freelander' => 'properties.series.freelander',
				'range_rover' => 'properties.series.range_rover',
				'range_rover_evoque' => 'properties.series.range_rover_evoque',
				'range_rover_sport' => 'properties.series.range_rover_sport',
				'other' => 'properties.series.other',
			],
			'lexus' => [
				'ct' => 'properties.series.ct',
				'es' => 'properties.series.es',
				'gs' => 'properties.series.gs',
				'gx' => 'properties.series.gx',
				'hs' => 'properties.series.hs',
				'is' => 'properties.series.is',
				'ls' => 'properties.series.ls',
				'lx' => 'properties.series.lx',
				'nx' => 'properties.series.nx',
				'rc' => 'properties.series.rc',
				'rx' => 'properties.series.rx',
				'sc' => 'properties.series.sc',
				'other' => 'properties.series.other',
			],
			'mazda' => [
				'2' => 'properties.series.2',
				'3' => 'properties.series.3',
				'323' => 'properties.series.323',
				'3_mps' => 'properties.series.3_mps',
				'5' => 'properties.series.5',
				'6' => 'properties.series.6',
				'626' => 'properties.series.626',
				'6_mps' => 'properties.series.6_mps',
				'929' => 'properties.series.929',
				'axela' => 'properties.series.axela',
				'biante' => 'properties.series.biante',
				'bongo' => 'properties.series.bongo',
				'bt_50' => 'properties.series.bt_50',
				'capella' => 'properties.series.capella',
				'cx_5' => 'properties.series.cx_5',
				'cx_7' => 'properties.series.cx_7',
				'cx_9' => 'properties.series.cx_9',
				'demio' => 'properties.series.demio',
				'familia' => 'properties.series.familia',
				'millenia' => 'properties.series.millenia',
				'mpv' => 'properties.series.mpv',
				'mx_3' => 'properties.series.mx_3',
				'mx_5' => 'properties.series.mx_5',
				'mx_6' => 'properties.series.mx_6',
				'premacy' => 'properties.series.premacy',
				'rx_7' => 'properties.series.rx_7',
				'rx_8' => 'properties.series.rx_8',
				'tribute' => 'properties.series.tribute',
				'xedos_6' => 'properties.series.xedos_6',
				'xedos_9' => 'properties.series.xedos_9',
				'other' => 'properties.series.other',
			],
			'mercedes_benz' => [
				'a_class' => 'properties.series.a_class',
				'b_class' => 'properties.series.b_class',
				'cla_class' => 'properties.series.cla_class',
				'clk_class' => 'properties.series.clk_class',
				'cls_class' => 'properties.series.cls_class',
				'cl_class' => 'properties.series.cl_class',
				'c_class' => 'properties.series.c_class',
				'e_class' => 'properties.series.e_class',
				'e_class_amg' => 'properties.series.e_class_amg',
				'gla_class' => 'properties.series.gla_class',
				'glc_class' => 'properties.series.glc_class',
				'gle_class' => 'properties.series.gle_class',
				'glk_class' => 'properties.series.glk_class',
				'gls_class' => 'properties.series.gls_class',
				'gl_class' => 'properties.series.gl_class',
				'g_class' => 'properties.series.g_class',
				'g_class_amg' => 'properties.series.g_class',
				'maybach' => 'properties.series.maybach',
				's_class' => 'properties.series.s_class',
				'm_class' => 'properties.series.m_class',
				'm_class_amg' => 'properties.series.m_class_amg',
				'r_class' => 'properties.series.r_class',
				'sl_class' => 'properties.series.sl_class',
				'sprinter' => 'properties.series.sprinter',
				'sprinter_classic' => 'properties.series.sprinter_classic',
				's_class' => 'properties.series.s_class',
				's_class_amg' => 'properties.series.s_class_amg',
				'viano' => 'properties.series.viano',
				'vito_v_class' => 'properties.series.vito_v_class',
				'w124' => 'properties.series.w124',
				'other' => 'properties.series.other',
			],
			'mitsubishi' => [
				'3000_gt' => 'properties.series.3000_gt',
				'airtrek' => 'properties.series.airtrek',
				'asx' => 'properties.series.asx',
				'carisma' => 'properties.series.carisma',
				'chariot' => 'properties.series.chariot',
				'colt' => 'properties.series.colt',
				'delica' => 'properties.series.delica',
				'diamante' => 'properties.series.diamante',
				'eclipse' => 'properties.series.eclipse',
				'galant' => 'properties.series.galant',
				'grandis' => 'properties.series.grandis',
				'i' => 'properties.series.i',
				'l200' => 'properties.series.l200',
				'lancer' => 'properties.series.lancer',
				'lancer_evolution' => 'properties.series.lancer_evolution',
				'legnum' => 'properties.series.legnum',
				'minica' => 'properties.series.minica',
				'mirage' => 'properties.series.mirage',
				'montero' => 'properties.series.montero',
				'montero_sport' => 'properties.series.montero_sport',
				'outlander' => 'properties.series.outlander',
				'pajero' => 'properties.series.pajero',
				'pajero_mini' => 'properties.series.pajero_mini',
				'pajero_pinin' => 'properties.series.pajero_pinin',
				'pajero_sport' => 'properties.series.pajero_sport',
				'rvr' => 'properties.series.rvr',
				'sigma' => 'properties.series.sigma',
				'space_star' => 'properties.series.space_star',
				'space_wagon' => 'properties.series.space_wagon',
				'other' => 'properties.series.other',
			],
			'nissan' => [
				'350z' => 'properties.series.350z',
				'almera' => 'properties.series.almera',
				'almera_classic' => 'properties.series.almera_classic',
				'bluebird' => 'properties.series.bluebird',
				'cefiro' => 'properties.series.cefiro',
				'cube' => 'properties.series.cube',
				'gt_r' => 'properties.series.gt_r',
				'juke' => 'properties.series.juke',
				'laurel' => 'properties.series.laurel',
				'march' => 'properties.series.march',
				'maxima' => 'properties.series.maxima',
				'micra' => 'properties.series.micra',
				'murano' => 'properties.series.murano',
				'navara' => 'properties.series.navara',
				'note' => 'properties.series.note',
				'pathfinder' => 'properties.series.pathfinder',
				'patrol' => 'properties.series.patrol',
				'primera' => 'properties.series.primera',
				'qashqai' => 'properties.series.qashqai',
				'qashqai_2' => 'properties.series.qashqai_2',
				'sentra' => 'properties.series.sentra',
				'serena' => 'properties.series.serena',
				'skyline' => 'properties.series.skyline',
				'sunny' => 'properties.series.sunny',
				'teana_terrano' => 'properties.series.teana_terrano',
				'tiida' => 'properties.series._tiida',
				'vanette' => 'properties.series.vanette',
				'wingroad' => 'properties.series.wingroad',
				'x_trail' => 'properties.series.x_trail',
				'other' => 'properties.series.other',
			],
			'opel' => [
				'admiral' => 'properties.series.admiral',
				'agila' => 'properties.series.agila',
				'antara' => 'properties.series.antara',
				'ascona' => 'properties.series.ascona',
				'astra' => 'properties.series.astra',
				'astra_gtc' => 'properties.series.astra_gtc',
				'astra_opc' => 'properties.series.astra_opc',
				'calibra' => 'properties.series.calibra',
				'combo' => 'properties.series.combo',
				'commodore' => 'properties.series.commodore',
				'corsa' => 'properties.series.corsa',
				'corsa_opc' => 'properties.series.corsa_opc',
				'frontera' => 'properties.series.frontera',
				'gt' => 'properties.series.gt',
				'insignia' => 'properties.series.insignia',
				'insignia_opc' => 'properties.series.insignia_opc',
				'kadett' => 'properties.series.kadett',
				'meriva' => 'properties.series.meriva',
				'mokka' => 'properties.series.mokka',
				'monterey' => 'properties.series.monterey',
				'movano' => 'properties.series.movano',
				'omega' => 'properties.series.omega',
				'rekord' => 'properties.series.rekord',
				'signum' => 'properties.series.signum',
				'sintra' => 'properties.series.sintra',
				'tigra' => 'properties.series.tigra',
				'vectra' => 'properties.series.vectra',
				'vita' => 'properties.series.vita',
				'vivaro' => 'properties.series.vivaro',
				'zafira' => 'properties.series.zafira',
				'other' => 'properties.series.other',
			],
			'peugeot' => [
				'1007' => 'properties.series.1007',
				'107' => 'properties.series.107',
				'2008' => 'properties.series.2008',
				'205' => 'properties.series.205',
				'206' => 'properties.series.206',
				'207' => 'properties.series.207',
				'208' => 'properties.series.208',
				'3008' => 'properties.series.3008',
				'301' => 'properties.series.301',
				'306' => 'properties.series.306',
				'307' => 'properties.series.307',
				'308' => 'properties.series.308',
				'309' => 'properties.series.309',
				'4007' => 'properties.series.4007',
				'4008' => 'properties.series.4008',
				'405' => 'properties.series.405',
				'406' => 'properties.series.406',
				'407' => 'properties.series.407',
				'408' => 'properties.series.408',
				'5008' => 'properties.series.5008',
				'505' => 'properties.series.505',
				'508' => 'properties.series.508',
				'605' => 'properties.series.605',
				'607' => 'properties.series.607',
				'806' => 'properties.series.806',
				'807' => 'properties.series.807',
				'boxer' => 'properties.series.boxer',
				'expert' => 'properties.series.expert',
				'partner' => 'properties.series.partner',
				'rcz' => 'properties.series.rcz',
				'other' => 'properties.series.other',
			],
			'porsche' => [
				'356' => 'properties.series.356',
				'718_boxster' => 'properties.series.718_boxster',
				'718_boxster_s' => 'properties.series.718_boxster_s',
				'718_cayman' => 'properties.series.718 cayman',
				'718_cayman_s' => 'properties.series.718_cayman_s',
				'911_carrera' => 'properties.series.911_carrera',
				'911_carrera_4' => 'properties.series.911_carrera_4',
				'911_carrera_4s' => 'properties.series.911_carrera_4s',
				'911_carrera_s' => 'properties.series.911_carrera_s',
				'911_gt2' => 'properties.series.911_gt2',
				'911_gt3' => 'properties.series.911_gt3',
				'911_targa_4s' => 'properties.series.911_targa_4s',
				'911_turbo' => 'properties.series.911_turbo',
				'911_turbo_s' => 'properties.series.911_turbo_s',
				'924' => 'properties.series.924',
				'944' => 'properties.series.944',
				'boxster' => 'properties.series.boxster',
				'boxster_s' => 'properties.series.boxster_s',
				'carrera gt' => 'properties.series.carrera gt',
				'cayenne' => 'properties.series.cayenne',
				'cayenne_gts' => 'properties.series.cayenne_gts',
				'cayenne_s' => 'properties.series.cayenne_s',
				'cayenne_turbo' => 'properties.series.cayenne_turbo',
				'cayenne_turbo_s' => 'properties.series.cayenne_turbo_s',
				'cayman' => 'properties.series.cayman',
				'cayman_s' => 'properties.series.cayman_s',
				'macan' => 'properties.series.macan',
				'macan_s' => 'properties.series.macan_s',
				'macan_turbo' => 'properties.series.macan_turbo',
				'panamera' => 'properties.series.panamera',
				'panamera_4' => 'properties.series.panamera_4',
				'panamera_4s' => 'properties.series.panamera_4s',
				'panamera gts' => 'properties.series.panamera gts',
				'panamera turbo' => 'properties.series.panamera turbo',
				'panamera_turbo_s' => 'properties.series.panamera_turbo_s',
				'other' => 'properties.series.other',
			],
			'renault' => [
				'19' => 'properties.series.19',
				'21' => 'properties.series.21',
				'25' => 'properties.series.25',
				'clio' => 'properties.series.clio',
				'clio_rs' => 'properties.series.clio_rs',
				'duster' => 'properties.series.duster',
				'espace' => 'properties.series.espace',
				'fluence' => 'properties.series.fluence',
				'grand_scenic' => 'properties.series.grand_scenic',
				'kangoo' => 'properties.series.kangoo',
				'kaptur' => 'properties.series.kaptur',
				'koleos' => 'properties.series.koleos',
				'laguna' => 'properties.series.laguna',
				'latitude' => 'properties.series.latitude',
				'logan' => 'properties.series.logan',
				'master' => 'properties.series.master',
				'megane' => 'properties.series.megane',
				'modus' => 'properties.series.modus',
				'safrane' => 'properties.series.safrane',
				'sandero' => 'properties.series.sandero',
				'sandero_stepway' => 'properties.series.sandero_stepway',
				'scenic' => 'properties.series.scenic',
				'symbol' => 'properties.series.symbol',
				'trafic' => 'properties.series.trafic',
				'twingo' => 'properties.series.twingo',
				'other' => 'properties.series.other',
			],
			'skoda' => [
				'fabia' => 'properties.series.fabia',
				'fabia_rs' => 'properties.series.fabia_rs',
				'felicia' => 'properties.series.felicia',
				'octavia' => 'properties.series.octavia',
				'octavia_rs' => 'properties.series.octavia_rs',
				'octavia_scout' => 'properties.series.octavia_scout',
				'praktik' => 'properties.series.praktik',
				'rapid' => 'properties.series.rapid',
				'roomster' => 'properties.series.roomster',
				'superb' => 'properties.series.superb',
				'yeti' => 'properties.series.yeti',
				'other' => 'properties.series.other',
			],
			'ssangyong' => [
				'actyon' => 'properties.series.actyon',
				'actyon_sports' => 'properties.series.actyon_sports',
				'istana' => 'properties.series.istana',
				'korando' => 'properties.series.korando',
				'korando_sports' => 'properties.series.korando_sports',
				'kyron' => 'properties.series.kyron',
				'musso' => 'properties.series.musso',
				'rexton' => 'properties.series.rexton',
				'rodius' => 'properties.series.rodius',
				'stavic' => 'properties.series.stavic',
				'other' => 'properties.series.other',
			],
			'subaru' => [
				'baja' => 'properties.series.baja',
				'forester' => 'properties.series.forester',
				'impreza' => 'properties.series.impreza',
				'legacy' => 'properties.series.legacy',
				'outback' => 'properties.series.outback',
				'r2' => 'properties.series.r2',
				'tribeca' => 'properties.series.tribeca',
				'vivio' => 'properties.series.vivio',
				'wrx' => 'properties.series.wrx',
				'wrx_sti' => 'properties.series.wrx_sti',
				'xv' => 'properties.series.xv',
				'other' => 'properties.series.other',
			],
			'suzuki' => [
				'aerio' => 'properties.series.aerio',
				'alto' => 'properties.series.alto',
				'baleno' => 'properties.series.baleno',
				'escudo' => 'properties.series.escudo',
				'every' => 'properties.series.every',
				'grand_vitara' => 'properties.series.grand_vitara',
				'ignis' => 'properties.series.ignis',
				'jimny' => 'properties.series.jimny',
				'kizashi' => 'properties.series.kizashi',
				'liana' => 'properties.series.liana',
				'samurai' => 'properties.series.samurai',
				'splash' => 'properties.series.splash',
				'swift' => 'properties.series.swift',
				'sx4' => 'properties.series.sx4',
				'vitara' => 'properties.series.vitara',
				'wagon_r' => 'properties.series.wagon_r',
				'xl7' => 'properties.series.xl7',
				'other' => 'properties.series.other',
			],
			'toyota' => [
				'4runner' => 'properties.series.4runner',
				'alphard' => 'properties.series.alphard',
				'auris' => 'properties.series.auris',
				'avensis' => 'properties.series.avensis',
				'caldina' => 'properties.series.caldina',
				'camry' => 'properties.series.camry',
				'carina' => 'properties.series.carina',
				'celica' => 'properties.series.celica',
				'chaser' => 'properties.series.chaser',
				'corolla' => 'properties.series.corolla',
				'corona' => 'properties.series.corona',
				'crown' => 'properties.series.crown',
				'estima' => 'properties.series.estima',
				'hiace' => 'properties.series.hiace',
				'highlander' => 'properties.series.highlander',
				'hilux' => 'properties.series.hilux',
				'land_cruiser' => 'properties.series.land_cruiser',
				'land_cruiser_prado' => 'properties.series.land_cruiser_prado',
				'mark_ii' => 'properties.series.mark_ii',
				'noah' => 'properties.series.noah',
				'previa' => 'properties.series.previa',
				'prius' => 'properties.series.prius',
				'rav4' => 'properties.series.rav4',
				'sequoia' => 'properties.series.sequoia',
				'sienna' => 'properties.series.sienna',
				'tundra' => 'properties.series.tundra',
				'venza' => 'properties.series.venza',
				'verso' => 'properties.series.verso',
				'vista' => 'properties.series.vista',
				'yaris' => 'properties.series.yaris',
				'other' => 'properties.series.other',
			],
			'volkswagen' => [
				'amarok' => 'properties.series.amarok',
				'beetle' => 'properties.series.beetle',
				'bora' => 'properties.series.bora',
				'caddy' => 'properties.series.caddy',
				'california' => 'properties.series.california',
				'caravelle' => 'properties.series.caravelle',
				'crafter  crosspolo' => 'properties.series.crafter  crosspolo',
				'eos' => 'properties.series.eos',
				'golf' => 'properties.series.golf',
				'golf_gti' => 'properties.series.golf_gti',
				'golf_plus' => 'properties.series.golf_plus',
				'golf_r' => 'properties.series.golf_r',
				'jetta' => 'properties.series.jetta',
				'kaefer' => 'properties.series.kaefer',
				'lupo' => 'properties.series.lupo',
				'multivan' => 'properties.series.multivan',
				'passat' => 'properties.series.passat',
				'passat_cc' => 'properties.series.passat_cc',
				'phaeton' => 'properties.series.phaeton',
				'pointer' => 'properties.series.pointer',
				'polo' => 'properties.series.polo',
				'scirocco' => 'properties.series.scirocco',
				'sharan' => 'properties.series.sharan',
				'tiguan' => 'properties.series.tiguan',
				'touareg' => 'properties.series.touareg',
				'touran' => 'properties.series.touran',
				'transporter' => 'properties.series.transporter',
				'up' => 'properties.series.up',
				'vento' => 'properties.series.vento',
				'other' => 'properties.series.other',
			],
			'volvo' => [
				'240' => 'properties.series.240',
				'340' => 'properties.series.340',
				'360' => 'properties.series.360',
				'440' => 'properties.series.440',
				'460' => 'properties.series.460',
				'480' => 'properties.series.480',
				'740' => 'properties.series.740',
				'760' => 'properties.series.760',
				'850' => 'properties.series.850',
				'940' => 'properties.series.940',
				'960' => 'properties.series.960',
				'c30' => 'properties.series.c30',
				'c70' => 'properties.series.c70',
				's40' => 'properties.series.s40',
				's60' => 'properties.series.s60',
				's70' => 'properties.series.s70',
				's80' => 'properties.series.s80',
				's90' => 'properties.series.s90',
				'v40' => 'properties.series.v40',
				'v40_cross_country' => 'properties.series.v40_cross_country',
				'v50' => 'properties.series.v50',
				'v60' => 'properties.series.v60',
				'v70' => 'properties.series.v70',
				'v90' => 'properties.series.v90',
				'xc60' => 'properties.series.xc60',
				'xc70' => 'properties.series.xc70',
				'xc90' => 'properties.series.xc90',
			],
			'other' => [

			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'auto_type',
		'title' => 'properties.auto_type',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.auto_type.description',
		'options' => [
		],
		'values' => [
			null => [
				'new' => 'properties.auto_type.new',
				'with_mileage' => 'properties.auto_type.with_mileage',
			],
		],
	],
	[
		'parent_id' => 'auto_type',
		'name' => 'mileage',
		'title' => 'properties.mileage',
		'type' => 'numeric',
		'default' => null,
		'description' => 'properties.mileage.description',
		'options' => [
			'min' => 0,
			'max' => null,
			'step' => 1,
			'format' => [0,',',' '],
			'view' => 'input', // input - поле ввода, select - выпадающий список
			'select-value' => null,
		],
		'values' => [
			'with_mileage' => [null],
		],
	],
	[
		'parent_id' => null,
		'name' => 'spare_part_type',
		'title' => 'properties.spare_part_type',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.spare_part_type.description',
		'options' => [
		],
		'values' => [
			null => [
				'autolight' => 'properties.spare_part_type.autolight',
				'accumulators' => 'properties.spare_part_type.accumulators',
				'engine' => 'properties.spare_part_type.engine',
				'spare_parts_for_maintenance' => 'properties.spare_part_type.spare_parts_for_maintenance',
				'body' => 'properties.spare_part_type.body',
				'suspension' => 'properties.spare_part_type.suspension',
				'steering' => 'properties.spare_part_type.steering',
				'salon' => 'properties.spare_part_type.salon',
				'cooling_system' => 'properties.spare_part_type.cooling_system',
				'glass' => 'properties.spare_part_type.glass',
				'fuel_and_exhaust_systems' => 'properties.spare_part_type.fuel_and_exhaust_systems',
				'brake_system' => 'properties.spare_part_type.brake_system',
				'transmission_and_drive' => 'properties.spare_part_type.transmission_and_drive',
				'electrical_equipment' => 'properties.spare_part_type.electrical_equipment',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_truck',
		'title' => 'properties.type_of_truck',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_truck.description',
		'options' => [
		],
		'values' => [
			null => [
				'tractors' => 'properties.type_of_truck.tractors',
				'trucks' => 'properties.type_of_truck.trucks',
				'trailers' => 'properties.type_of_truck.trailers',
				'buses' => 'properties.type_of_truck.buses',
				'motorhomes' => 'properties.type_of_truck.motorhomes',
				'truck_cranes_and_cranes' => 'properties.type_of_truck.truck_cranes_and_cranes',
				'bulldozers_and_graders' => 'properties.type_of_truck.bulldozers_and_graders',
				'communal_equipment' => 'properties.type_of_truck.communal_equipment',
				'light_transport' => 'properties.type_of_truck.light_transport',
				'loaders' => 'properties.type_of_truck.loaders',
				'agricultura_machinery' => 'properties.type_of_truck.agricultura_machinery',
				'construction_machinery' => 'properties.type_of_truck.construction_machinery',
				'logging_equipment' => 'properties.type_of_truck.logging_equipment',
				'excavators' => 'properties.type_of_truck.excavators',
				'other_special_equipment' => 'properties.type_of_truck.other_special_equipment',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_moto',
		'title' => 'properties.type_of_moto',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_moto.description',
		'options' => [
		],
		'values' => [
			null => [
				'buggy' => 'properties.type_of_moto.buggy',
				'atvs' => 'properties.type_of_moto.atvs',
				'karting' => 'properties.type_of_moto.karting',
				'quadrocycles' => 'properties.type_of_moto.quadrocycles',
				'mopeds_and_scooters' => 'properties.type_of_moto.mopeds_and_scooters',
				'motorcycles' => 'properties.type_of_moto.motorcycles',
				'snowmobiles' => 'properties.type_of_moto.snowmobiles',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_water_transport',
		'title' => 'properties.type_of_water_transport',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_water_transport.description',
		'options' => [
		],
		'values' => [
			null => [
				'rowing_boats' => 'properties.type_of_water_transport.rowing_boats',
				'hydrocycles' => 'properties.type_of_water_transport.hydrocycles',
				'boats_and_yachts' => 'properties.type_of_water_transport.boats_and_yachts',
				'kayaks_and_canoes' => 'properties.type_of_water_transport.kayaks_and_canoes',
				'motor_boats' => 'properties.type_of_water_transport.motor_boats',
				'inflatable_boat' => 'properties.type_of_water_transport.inflatable_boat',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'year_of_issue',
		'title' => 'properties.year_of_issue',
		'type' => 'numeric',
		'default' => null,
		'description' => 'properties.year_of_issue.description',
		'options' => [
			'min' => 1950,
			'max' => 2017,
			'step' => 1,
			'format' => [0,',',''],
			'view' => 'select', // input - поле ввода, select - выпадающий список
			'select-value' => 'properties.year_of_issue.value',
		],
		'values' => [
			null => [null],
		],
	],
	[
		'parent_id' => null,
		'name' => 'transmission',
		'title' => 'properties.transmission',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.transmission.description',
		'options' => [
		],
		'values' => [
			null => [
				'mechanics' => 'properties.transmission.mechanics',
				'auto' => 'properties.transmission.auto',
				'robot' => 'properties.transmission.robot',
				'aviator' => 'properties.transmission.aviator',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'fuel_type',
		'title' => 'properties.fuel_type',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.fuel_type.description',
		'options' => [
		],
		'values' => [
			null => [
				'petrol' => 'properties.fuel_type.petrol',
				'diesel' => 'properties.fuel_type.diesel',
				'hybrid' => 'properties.fuel_type.hybrid',
				'electro' => 'properties.fuel_type.electro',
				'gas' => 'properties.fuel_type.gas',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_real_estate',
		'title' => 'properties.type_of_real_estate',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_real_estate.description',
		'options' => [
		],
		'values' => [
			null => [
				'rent' => 'properties.type_of_real_estate.rent', // сдам
				'take_off' => 'properties.type_of_real_estate.take_off', // сниму
				'selling' => 'properties.type_of_real_estate.selling', // продам
				'buy' => 'properties.type_of_real_estate.buy', // куплю
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_apartments',
		'title' => 'properties.type_of_apartments',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_apartments.description',
		'options' => [
		],
		'values' => [
			null => [
				'new_building' => 'properties.type_of_apartments.new_building',
				'secondary_housing' => 'properties.type_of_apartments.secondary_housing',
			],
		],
	],
	[
		'parent_id' => 'type_of_real_estate',
		'name' => 'type_of_room',
		'title' => 'properties.type_of_room',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_room.description',
		'options' => [
		],
		'values' => [
			'rent' => [
				'short' => 'properties.type_of_room.short',
				'long' => 'properties.type_of_room.long',
			],
			'take_off' => [
				'short' => 'properties.type_of_room.short',
				'long' => 'properties.type_of_room.long',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_country_house',
		'title' => 'properties.type_of_country_house',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_country_house.description',
		'options' => [
		],
		'values' => [
			'rent' => [
				'short' => 'properties.type_of_country_house.short',
				'long' => 'properties.type_of_country_house.long',
			],
			'take_off' => [
				'short' => 'properties.type_of_country_house.short',
				'long' => 'properties.type_of_country_house.long',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_land',
		'title' => 'properties.type_of_land',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_land.description',
		'options' => [
		],
		'values' => [
			null => [
				'settlements' => 'properties.type_of_land.settlements',
				'agricultural_purpose' => 'properties.type_of_land.agricultural_purpose',
				'industrial_use' => 'properties.type_of_land.industrial_use',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_garage',
		'title' => 'properties.type_of_garage',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_garage.description',
		'options' => [
		],
		'values' => [
			null => [
				'garage' => 'properties.type_of_garage.garage',
				'car_place' => 'properties.type_of_garage.car_place',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'number_of_rooms',
		'title' => 'properties.number_of_rooms',
		'type' => 'numeric',
		'default' => null,
		'description' => 'properties.number_of_rooms.description',
		'options' => [
			'min' => 1,
			'max' => 10,
			'step' => 1,
			'format' => [0,',',''],
			'view' => 'select', // input - поле ввода, select - выпадающий список
			'select-value' => 'properties.number_of_rooms.value',
		],
		'values' => [
			null => [null],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_commercial_property',
		'title' => 'properties.type_of_commercial_property',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_commercial_property.description',
		'options' => [
		],
		'values' => [
			null => [
				'hotel' => 'properties.type_of_commercial_property.hotel',
				'office_space' => 'properties.type_of_commercial_property.office_space',
				'catering' => 'properties.type_of_commercial_property.catering',
				'free_room' => 'properties.type_of_commercial_property.free_room',
				'production_room' => 'properties.type_of_commercial_property.production_room',
				'warehouse_space' => 'properties.type_of_commercial_property.warehouse_space',
				'commercial_premises' => 'properties.type_of_commercial_property.commercial_premises',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_service',
		'title' => 'properties.type_of_service',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_service.description',
		'options' => [

		],
		'values' => [
			null => [
				'lawyers_legal' => 'properties.type_of_service.lawyers_legal',
				'real_estate_agency' => 'properties.type_of_service.real_estate_agency',
				'cargo_transportation' => 'properties.type_of_service.cargo_transportation',
				'taxi' => 'taxi',
				'construction_materials' => 'properties.type_of_service.construction_materials',
				'finishing' => 'properties.type_of_service.finishing',
				'security' => 'properties.type_of_service.security',
				'repair_of_household_appliances' => 'properties.type_of_service.repair_of_household_appliances',
				'control_course' => 'properties.type_of_service.control_course',
				'videography' => 'properties.type_of_service.videography',
				'beauty_health' => 'properties.type_of_service.beauty_health',
				'tourism' => 'properties.type_of_service.tourism',
				'education' => 'properties.type_of_service.education',
				'advertising' => 'properties.type_of_service.advertising',
				'ritual' => 'properties.type_of_service.ritual',
				'leisure_saunas_massage' => 'properties.type_of_service.leisure_saunas_massage',
				'festive_animation' => 'properties.type_of_service.festive_animation',
				'cafes_and_restaurants' => 'properties.type_of_service.cafes_and_restaurants',
				'flowers' => 'properties.type_of_service.flowers',
				'it_internet_telecom' => 'properties.type_of_service.it_internet_telecom',
				'domestic_services' => 'properties.type_of_service.domestic_services',
				'business_services' => 'properties.type_of_service.business_services',
				'courier_services' => 'properties.type_of_service.courier_services',
				'master_for_an_hour' => 'properties.type_of_service.master_for_an_hour',
				'nanny' => 'properties.type_of_service.nanny',
				'training_courses' => 'properties.type_of_service.training_courses',
				'food' => 'properties.type_of_service.food',
				'garden_accomplishment' => 'properties.type_of_service.garden_accomplishment',
				'cleaning' => 'properties.type_of_service.cleaning',
				'care_for_the_elderly' => 'properties.type_of_service.care_for_the_elderly',
				'other_services' => 'properties.type_of_service.other_services',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_clothes',
		'title' => 'properties.type_of_clothes',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_clothes.description',
		'options' => [

		],
		'values' => [
			null => [
				'womens_clothing' => 'properties.type_of_clothes.womens_clothing',
				'womens_shoes' => 'properties.type_of_clothes.womens_shoes',
				'womens_accessories' => 'properties.type_of_clothes.womens_accessories',
				'mens_clothing' => 'properties.type_of_clothes.mens_clothing',
				'mens_footwear' => 'properties.type_of_clothes.mens_footwear',
				'mens_accessories' => 'properties.type_of_clothes.mens_accessories',
			],
		],
	],
	[
		'parent_id' => 'type_of_clothes',
		'name' => 'womens_element_of_clothing',
		'title' => 'properties.element_of_clothing',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.element_of_clothing.description',
		'options' => [

		],
		'values' => [
			'womens_clothing' => [
				'pants' => 'properties.element_of_clothing.pants',
				'outerwear' => 'properties.element_of_clothing.outerwear',
				'jeans' => 'properties.element_of_clothing.jeans',
				'swimsuits' => 'properties.element_of_clothing.swimsuits',
				'underwear' => 'properties.element_of_clothing.underwear',
				'jackets_and_suits' => 'properties.element_of_clothing.jackets_and_suits',
				'dresses_and_skirts' => 'properties.element_of_clothing.dresses_and_skirts',
				'shirts_and_blouses' => 'properties.element_of_clothing.shirts_and_blouses',
				'wedding_dresses' => 'properties.element_of_clothing.wedding_dresses',
				'tops_and_t_shirts' => 'properties.element_of_clothing.tops_and_t_shirts',
				'knitwear' => 'properties.element_of_clothing.knitwear',
				'other' => 'properties.element_of_clothing.other',
			],
		],
	],
	[
		'parent_id' => 'type_of_clothes',
		'name' => 'mens_element_of_clothing',
		'title' => 'properties.element_of_clothing',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.element_of_clothing.description',
		'options' => [

		],
		'values' => [
			'mens_clothing' => [
				'pants' => 'properties.element_of_clothing.pants',
				'outerwear' => 'properties.element_of_clothing.outerwear',
				'jeans' => 'properties.element_of_clothing.jeans',
				'jackets_and_suits' => 'properties.element_of_clothing.jackets_and_suits',
				'shirts' => 'properties.element_of_clothing.shirts',
				'jersey_and_t_shirts' => 'properties.element_of_clothing.jersey_and_t_shirts',
				'other' => 'properties.element_of_clothing.other',
			],
		],
	],
	[
		'parent_id' => 'type_of_clothes',
		'name' => 'type_of_shoes',
		'title' => 'properties.type_of_shoes',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_shoes.description',
		'options' => [

		],
		'values' => [
			'womens_shoes' => [
				'shoes_winter' => 'properties.type_of_shoes.shoes_winter',
				'summer_shoes' => 'properties.type_of_shoes.summer_shoes',
				'autumn_spring_shoes' => 'properties.type_of_shoes.autumn_spring_shoes',
				'beach_shoes' => 'properties.type_of_shoes.beach_shoes',
				'sport_shoes' => 'properties.type_of_shoes.sport_shoes',
				'other_shoes' => 'properties.type_of_shoes.other_shoes',
			],
			'mens_footwear' => [
				'shoes_winter' => 'properties.type_of_shoes.shoes_winter',
				'summer_shoes' => 'properties.type_of_shoes.summer_shoes',
				'autumn_spring_shoes' => 'properties.type_of_shoes.autumn_spring_shoes',
				'beach_shoes' => 'properties.type_of_shoes.beach_shoes',
				'sport_shoes' => 'properties.type_of_shoes.sport_shoes',
				'other_shoes' => 'properties.type_of_shoes.other_shoes',
			],
		],
	],
	[
		'parent_id' => 'womens_element_of_clothing',
		'name' => 'size_of_womens_clothing',
		'title' => 'properties.size',
		'type' => 'select',
		'default' => 'no_size',
		'description' => 'properties.size.description',
		'options' => [
		],
		'values' => [
			'pants' => [
				'no_size' => 'properties.size.no_size',
				'40_42_XS' => 'properties.size.40_42_XS',
				'42_44_S' => 'properties.size.42_44_S',
				'44_46_M' => 'properties.size.44_46_M',
				'46_48_L' => 'properties.size.46_48_L',
				'48_50_XL' => 'properties.size.48_50_XL',
				'50_XXL' => 'properties.size.50_XXL',
			],
			'outerwear' => [
				'no_size' => 'properties.size.no_size',
				'40_42_XS' => 'properties.size.40_42_XS',
				'42_44_S' => 'properties.size.42_44_S',
				'44_46_M' => 'properties.size.44_46_M',
				'46_48_L' => 'properties.size.46_48_L',
				'48_50_XL' => 'properties.size.48_50_XL',
				'50_XXL' => 'properties.size.50_XXL',
			],
			'jeans' => [
				'no_size' => 'properties.size.no_size',
				'25' => 'properties.size.25',
				'26' => 'properties.size.26',
				'27' => 'properties.size.27',
				'28' => 'properties.size.28',
				'29' => 'properties.size.29',
				'30' => 'properties.size.30',
				'31' => 'properties.size.31',
				'32' => 'properties.size.32',
				'33' => 'properties.size.33',
				'more_34' => 'properties.size.more_34',
			],
			'swimsuits' => [
				'no_size' => 'properties.size.no_size',
				'40_42_XS' => 'properties.size.40_42_XS',
				'42_44_S' => 'properties.size.42_44_S',
				'44_46_M' => 'properties.size.44_46_M',
				'46_48_L' => 'properties.size.46_48_L',
				'48_50_XL' => 'properties.size.48_50_XL',
				'50_XXL' => 'properties.size.50_XXL',
			],
			'underwear' => [
				'no_size' => 'properties.size.no_size',
				'40_42_XS' => 'properties.size.40_42_XS',
				'42_44_S' => 'properties.size.42_44_S',
				'44_46_M' => 'properties.size.44_46_M',
				'46_48_L' => 'properties.size.46_48_L',
				'48_50_XL' => 'properties.size.48_50_XL',
				'50_XXL' => 'properties.size.50_XXL',
			],
			'jackets_and_suits' => [
				'no_size' => 'properties.size.no_size',
				'40_42_XS' => 'properties.size.40_42_XS',
				'42_44_S' => 'properties.size.42_44_S',
				'44_46_M' => 'properties.size.44_46_M',
				'46_48_L' => 'properties.size.46_48_L',
				'48_50_XL' => 'properties.size.48_50_XL',
				'50_XXL' => 'properties.size.50_XXL',
			],
			'dresses_and_skirts' => [
				'no_size' => 'properties.size.no_size',
				'40_42_XS' => 'properties.size.40_42_XS',
				'42_44_S' => 'properties.size.42_44_S',
				'44_46_M' => 'properties.size.44_46_M',
				'46_48_L' => 'properties.size.46_48_L',
				'48_50_XL' => 'properties.size.48_50_XL',
				'50_XXL' => 'properties.size.50_XXL',
			],
			'shirts_and_blouses' => [
				'no_size' => 'properties.size.no_size',
				'40_42_XS' => 'properties.size.40_42_XS',
				'42_44_S' => 'properties.size.42_44_S',
				'44_46_M' => 'properties.size.44_46_M',
				'46_48_L' => 'properties.size.46_48_L',
				'48_50_XL' => 'properties.size.48_50_XL',
				'50_XXL' => 'properties.size.50_XXL',
			],
			'wedding_dresses' => [
				'no_size' => 'properties.size.no_size',
				'40_42_XS' => 'properties.size.40_42_XS',
				'42_44_S' => 'properties.size.42_44_S',
				'44_46_M' => 'properties.size.44_46_M',
				'46_48_L' => 'properties.size.46_48_L',
				'48_50_XL' => 'properties.size.48_50_XL',
				'50_XXL' => 'properties.size.50_XXL',
			],
			'tops_and_t_shirts' => [
				'no_size' => 'properties.size.no_size',
				'40_42_XS' => 'properties.size.40_42_XS',
				'42_44_S' => 'properties.size.42_44_S',
				'44_46_M' => 'properties.size.44_46_M',
				'46_48_L' => 'properties.size.46_48_L',
				'48_50_XL' => 'properties.size.48_50_XL',
				'50_XXL' => 'properties.size.50_XXL',
			],
			'knitwear' => [
				'no_size' => 'properties.size.no_size',
				'40_42_XS' => 'properties.size.40_42_XS',
				'42_44_S' => 'properties.size.42_44_S',
				'44_46_M' => 'properties.size.44_46_M',
				'46_48_L' => 'properties.size.46_48_L',
				'48_50_XL' => 'properties.size.48_50_XL',
				'50_XXL' => 'properties.size.50_XXL',
			],
			'other' => [
				'no_size' => 'properties.size.no_size',
				'40_42_XS' => 'properties.size.40_42_XS',
				'42_44_S' => 'properties.size.42_44_S',
				'44_46_M' => 'properties.size.44_46_M',
				'46_48_L' => 'properties.size.46_48_L',
				'48_50_XL' => 'properties.size.48_50_XL',
				'50_XXL' => 'properties.size.50_XXL',
			],
		],
	],
	[
		'parent_id' => 'mens_element_of_clothing',
		'name' => 'size_of_mens_clothing',
		'title' => 'properties.size',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.size.description',
		'options' => [
		],
		'values' => [
			'pants' => [
				'no_size' => 'properties.size.no_size',
				'42_44_XS' => 'properties.size.42_44_XS',
				'44_46_S' => 'properties.size.44_46_S',
				'46_48_M' => 'properties.sizeg.46_48_M',
				'48_50_L' => 'properties.sizeg.48_50_L',
				'50_52_XL' => 'properties.size.50_52_XL',
				'52_54_XXL' => 'properties.size.52_54_XXL',
				'54_XXXL' => 'properties.size.54_XXXL',
			],
			'outerwear' => [
				'no_size' => 'properties.size.no_size',
				'42_44_XS' => 'properties.size.42_44_XS',
				'44_46_S' => 'properties.size.44_46_S',
				'46_48_M' => 'properties.sizeg.46_48_M',
				'48_50_L' => 'properties.sizeg.48_50_L',
				'50_52_XL' => 'properties.size.50_52_XL',
				'52_54_XXL' => 'properties.size.52_54_XXL',
				'54_XXXL' => 'properties.size.54_XXXL',
			],
			'jeans' => [
				'no_size' => 'properties.size.no_size',
				'29' => 'properties.size.29',
				'30' => 'properties.size.30',
				'31' => 'properties.size.31',
				'32' => 'properties.size.32',
				'33' => 'properties.size.33',
				'34' => 'properties.size.34',
				'35' => 'properties.size.35',
				'36' => 'properties.size.36',
				'37' => 'properties.size.37',
				'more_38' => 'properties.size.more_38',
			],
			'jackets_and_suits' => [
				'no_size' => 'properties.size.no_size',
				'42_44_XS' => 'properties.size.42_44_XS',
				'44_46_S' => 'properties.size.44_46_S',
				'46_48_M' => 'properties.sizeg.46_48_M',
				'48_50_L' => 'properties.sizeg.48_50_L',
				'50_52_XL' => 'properties.size.50_52_XL',
				'52_54_XXL' => 'properties.size.52_54_XXL',
				'54_XXXL' => 'properties.size.54_XXXL',
			],
			'shirts' => [
				'no_size' => 'properties.size.no_size',
				'42_44_XS' => 'properties.size.42_44_XS',
				'44_46_S' => 'properties.size.44_46_S',
				'46_48_M' => 'properties.sizeg.46_48_M',
				'48_50_L' => 'properties.sizeg.48_50_L',
				'50_52_XL' => 'properties.size.50_52_XL',
				'52_54_XXL' => 'properties.size.52_54_XXL',
				'54_XXXL' => 'properties.size.54_XXXL',
			],
			'jersey_and_t_shirts' => [
				'no_size' => 'properties.size.no_size',
				'42_44_XS' => 'properties.size.42_44_XS',
				'44_46_S' => 'properties.size.44_46_S',
				'46_48_M' => 'properties.sizeg.46_48_M',
				'48_50_L' => 'properties.sizeg.48_50_L',
				'50_52_XL' => 'properties.size.50_52_XL',
				'52_54_XXL' => 'properties.size.52_54_XXL',
				'54_XXXL' => 'properties.size.54_XXXL',
			],
			'other' => [
				'no_size' => 'properties.size.no_size',
				'42_44_XS' => 'properties.size.42_44_XS',
				'44_46_S' => 'properties.size.44_46_S',
				'46_48_M' => 'properties.sizeg.46_48_M',
				'48_50_L' => 'properties.sizeg.48_50_L',
				'50_52_XL' => 'properties.size.50_52_XL',
				'52_54_XXL' => 'properties.size.52_54_XXL',
				'54_XXXL' => 'properties.size.54_XXXL',
			],
		],
	],
	[
		'parent_id' => 'type_of_clothes',
		'name' => 'size_of_womens_shoes',
		'title' => 'properties.size',
		'type' => 'numeric',
		'default' => 0,
		'description' => 'properties.size.description',
		'options' => [
			'min' => 35,
			'max' => 41,
			'step' => 1,
			'format' => [0,',',' '],
			'view' => 'select', // input - поле ввода, select - выпадающий список
			'select-value' => 'properties.size_of_womens_shoes.value',
		],
		'values' => [
			'womens_shoes' => [null],
		],
	],
	[
		'parent_id' => 'type_of_clothes',
		'name' => 'size_of_mens_shoes',
		'title' => 'properties.size',
		'type' => 'numeric',
		'default' => 0,
		'description' => 'properties.size.description',
		'options' => [
			'min' => 40,
			'max' => 46,
			'step' => 1,
			'format' => [0,',',' '],
			'view' => 'select', // input - поле ввода, select - выпадающий список
			'select-value' => 'properties.size_of_mens_shoes.value',
		],
		'values' => [
			'mens_shoes' => [null],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_children_clothes',
		'title' => 'properties.type_of_children_clothes',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_children_clothes.description',
		'options' => [
		],
		'values' => [
			null => [
				'clothes_for_girls' => 'properties.type_of_children_clothes.clothes_for_girls',
				'clothes_for_boys' => 'properties.type_of_children_clothes.clothes_for_boys',
				'shoes_for_girls' => 'properties.type_of_children_clothes.shoes_for_girls',
				'shoes_for_boys' => 'properties.type_of_children_clothes.shoes_for_boys',
			],
		],
	],
	[
		'parent_id' => 'type_of_children_clothes',
		'name' => 'element_of_children_clothes',
		'title' => 'properties.element_of_children_clothes',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.element_of_children_clothes.description',
		'options' => [
		],
		'values' => [
			'clothes_for_girls' => [
				'pants' => 'properties.element_of_children_clothes.pants',
				'outerwear' => 'properties.element_of_children_clothes.outerwear',
				'overalls_and_body' => 'properties.element_of_children_clothes.overalls_and_body',
				'pajamas' => 'properties.element_of_children_clothes.pajamas',
				'dresses_and_skirts' => 'properties.element_of_children_clothes.dresses_and_skirts',
				'knitwear' => 'properties.element_of_children_clothes.knitwear',
				'caps_mittens_scarves' => 'properties.element_of_children_clothes.caps_mittens_scarves',
				'other' => 'properties.element_of_children_clothes.other',
			],
			'clothes_for_boys' => [
				'pants' => 'properties.element_of_children_clothes.pants',
				'shirts' => 'properties.element_of_children_clothes.shirts',
				'outerwear' => 'properties.element_of_children_clothes.outerwear',
				'overalls_and_body' => 'properties.element_of_children_clothes.overalls_and_body',
				'pajamas' => 'properties.element_of_children_clothes.pajamas',
				'knitwear' => 'properties.element_of_children_clothes.knitwear',
				'caps_mittens_scarves' => 'properties.element_of_children_clothes.caps_mittens_scarves',
				'other' => 'properties.element_of_children_clothes.other',
			],
		],
	],
	[
		'parent_id' => 'type_of_children_clothes',
		'name' => 'type_of_children_shoes',
		'title' => 'properties.type_of_shoes',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_shoes.description',
		'options' => [

		],
		'values' => [
			'shoes_for_boys' => [
				'shoes_winter' => 'properties.type_of_shoes.shoes_winter',
				'summer_shoes' => 'properties.type_of_shoes.summer_shoes',
				'autumn_spring_shoes' => 'properties.type_of_shoes.autumn_spring_shoes',
				'beach_shoes' => 'properties.type_of_shoes.beach_shoes',
				'sport_shoes' => 'properties.type_of_shoes.sport_shoes',
				'other_shoes' => 'properties.type_of_shoes.other_shoes',
			],
			'shoes_for_girls' => [
				'shoes_winter' => 'properties.type_of_shoes.shoes_winter',
				'summer_shoes' => 'properties.type_of_shoes.summer_shoes',
				'autumn_spring_shoes' => 'properties.type_of_shoes.autumn_spring_shoes',
				'beach_shoes' => 'properties.type_of_shoes.beach_shoes',
				'sport_shoes' => 'properties.type_of_shoes.sport_shoes',
				'other_shoes' => 'properties.type_of_shoes.other_shoes',
			],
		],
	],
	[
		'parent_id' => 'element_of_children_clothes',
		'name' => 'size_of_children_clothing',
		'title' => 'properties.size',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.size.description',
		'options' => [
		],
		'values' => [
			null => [
				'no_size' => 'properties.size.no_size',
				'50_56_sm' => 'properties.size.50_56_sm',
				'62_68_sm' => 'properties.size.62_68_sm',
				'74_80_sm' => 'properties.size.74_80_sm',
				'86_92_sm' => 'properties.size.86_92_sm',
				'98_104_sm' => 'properties.size.98_104_sm',
				'110_116_sm' => 'properties.size.110_116_sm',
				'122_128_sm' => 'properties.size.122_128_sm',
				'134_140_sm' => 'properties.size.134_140_sm',
				'146_152_sm' => 'properties.size.146_152_sm',
			],
		],

	],
	[
		'parent_id' => 'type_of_children_clothes',
		'name' => 'size_of_children_shoes',
		'title' => 'properties.size',
		'type' => 'numeric',
		'default' => 0,
		'description' => 'properties.size.description',
		'options' => [
			'min' => 19,
			'max' => 36,
			'step' => 1,
			'format' => [0,',',' '],
			'view' => 'select', // input - поле ввода, select - выпадающий список
			'select-value' => 'properties.size_of_children_shoes.value',
		],
		'values' => [
			'shoes_for_girls' => [null],
			'shoes_for_boys' => [null],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_products_for_children',
		'title' => 'properties.type_of_products_for_children',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_products_for_children.description',
		'options' => [
		],
		'values' => [
			null => [
				'car_seats' => 'properties.type_of_products_for_children.car_seats',
				'bicycles_and_scooters' => 'properties.type_of_products_for_children.bicycles_and_scooters',
				'childrens_furniture' => 'properties.type_of_products_for_children.childrens_furniture',
				'baby_carriages' => 'properties.type_of_products_for_children.baby_carriages',
				'toys' => 'properties.type_of_products_for_children.toys',
				'bed_dress' => 'properties.type_of_products_for_children.bed_dress',
				'feeding_products' => 'properties.type_of_products_for_children.feeding_products',
				'goods_for_bathing' => 'properties.type_of_products_for_children.goods_for_bathing',
				'goods_for_school' => 'properties.type_of_products_for_children.goods_for_school',
			],
		],
	],
	[
		'parent_id' => 'type_of_products_for_children',
		'name' => 'type_of_childrens_furniture',
		'title' => 'properties.type_of_childrens_furniture',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_childrens_furniture.description',
		'options' => [
		],
		'values' => [
			'childrens_furniture' => [
				'bedrooms' => 'properties.type_of_childrens_furniture.bedrooms',
				'tables' => 'properties.type_of_childrens_furniture.tables',
				'chairs' => 'properties.type_of_childrens_furniture.chairs',
				'beds' => 'properties.type_of_childrens_furniture.beds',
				'cabinets' => 'properties.type_of_childrens_furniture.cabinets',
				'other_furniture' => 'properties.type_of_childrens_furniture.other_furniture',
			],
		],
	],
	[
		'parent_id' => null,
		'name' => 'type_of_jewelry',
		'title' => 'properties.type_of_jewelry',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_jewelry.description',
		'options' => [
		],
		'values' => [
			null => [
				'bijouterie' => 'properties.type_of_jewelry.bijouterie',
				'clock' => 'properties.type_of_jewelry.clock',
				'jewelry' => 'properties.type_of_jewelry.jewelry',
			],
		],
	],
	[
		'parent_id' => 'type_of_jewelry',
		'name' => 'type_of_bijouterie',
		'title' => 'properties.type_of_bijouterie',
		'type' => 'select',
		'default' => null,
		'description' => 'properties.type_of_bijouterie.description',
		'options' => [
		],
		'values' => [
			'bijouterie' => [
				'rings' => 'properties.type_of_bijouterie.rings',
				'conversations' => 'properties.type_of_bijouterie.conversations',
				'bracelets' => 'properties.type_of_bijouterie.bracelets',
				'earrings' => 'properties.type_of_bijouterie.earrings',
				'pendants' => 'properties.type_of_bijouterie.pendants',
				'other' => 'properties.type_of_bijouterie.other',
			],
			'jewelry' => [
				'rings' => 'properties.type_of_bijouterie.rings',
				'conversations' => 'properties.type_of_bijouterie.conversations',
				'bracelets' => 'properties.type_of_bijouterie.bracelets',
				'earrings' => 'properties.type_of_bijouterie.earrings',
				'pendants' => 'properties.type_of_bijouterie.pendants',
				'other' => 'properties.type_of_bijouterie.other',
			],
		],
	],
];